// Generated by Wrangler by running `wrangler types`

interface Env {
	ModeratorAgent: DurableObjectNamespace<import("./src/index").ModeratorAgentClass>;
	SpecialistAgent: DurableObjectNamespace<import("./src/index").SpecialistAgentClass>;
	RefuterAgent: DurableObjectNamespace<import("./src/index").RefuterAgentClass>;
	JuryAgent: DurableObjectNamespace<import("./src/index").JuryAgentClass>;
	AI: Ai;
}
interface Env {
	CLOUDFLARE_ACCOUNT_ID: any;
	CLOUDFLARE_OBSERVABILITY_TOKEN: any;
	WORKER_API_KEY: any;
	AGENTIC_WORKER_API_KEY: any;
	AI_GATEWAY_TOKEN: any;
	CF_BROWSER_RENDER_TOKEN: any;
	STITCH_API_KEY: any;
	JULES_API_KEY: any;
}
